services:
  - name: techtobot
    type: web
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: SESSION
        value: Media_search
      - key: API_ID
        value: "<your_api_id>"
      - key: API_HASH
        value: "<your_api_hash>"
      - key: BOT_TOKEN
        value: "<your_bot_token>"
      - key: CACHE_TIME
        value: "300"
      - key: USE_CAPTION_FILTER
        value: "False"
      - key: PICS
        value: "https://telegra.ph/file/7e56d907542396289fee4.jpg"
      - key: ADMINS
        value: "<your_admin_id>"
      - key: CHANNELS
        value: "0"
      - key: AUTH_USERS
        value: ""
      - key: DATABASE_URI
        value: "<your_mongodb_uri>"
      - key: DATABASE_NAME
        value: "Rajappan"
      - key: COLLECTION_NAME
        value: "Telegram_files"
      - key: LOG_CHANNEL
        value: "0"
      - key: SUPPORT_CHAT
        value: "TECHTOAM"
      - key: IMDB
        value: "True"
      - key: SPELL_CHECK_REPLY
        value: "True"
      - key: PROTECT_CONTENT
        value: "False"
